### ISSUE TITLE
这个sdk没有使用strict模式，导致在调试的时候有些资源没有及时关闭。

### ISSUE THREAD

**Issue by devilived** [MobClub/SMSSDK-for-Android#5]
java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.io.FileInputStream.<init>(FileInputStream.java:151)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at java.io.FileReader.<init>(FileReader.java:58)
        at com.mob.tools.utils.DeviceHelper.cx(DeviceHelper.java:3589)
        at com.mob.commons.authorize.a.a(Authorizer.java:461)
        at com.mob.commons.authorize.a.a(Authorizer.java:44)
        at com.mob.commons.authorize.a$2.run(Authorizer.java:293)

**Comment by mz5210** [comment]
> java.lang.Throwable: Explicit termination method 'close' not called
> at dalvik.system.CloseGuard.open(CloseGuard.java:223)
> at java.io.FileInputStream.(FileInputStream.java:151)
> at java.io.FileInputStream.(FileInputStream.java:103)
> at java.io.FileReader.(FileReader.java:58)
> at com.mob.tools.utils.DeviceHelper.cx(DeviceHelper.java:3589)
> at com.mob.commons.authorize.a.a(Authorizer.java:461)
> at com.mob.commons.authorize.a.a(Authorizer.java:44)
> at com.mob.commons.authorize.a$2.run(Authorizer.java:293)

你使用的SDK版本是多少，现在已经更新到3.5.2版本了，更新试一下？
